### ISSUE TITLE
Extension doesn't work with Kani's development version

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani-vscode-extension#34] opened 2023-02-14 22:52 UTC
There are only a few cases where I install the `kani-verifier` in my computers. The rest of the time, I use an almost up-to-date development version.

The problem is that the extension doesn't pick up `kani` or `cargo kani` from `PATH` (it's strange because the installed version works), so it's not possible to use the development version to debug expected issues in the next Kani releases (e.g., #31).

**Comment by jaisnan** [comment] 2023-02-14 23:34
I was able to reproduce this bug. Thanks for pointing it out!

**Comment by jaisnan** [comment] 2023-05-12 17:22
Relevant code - https://github.com/model-checking/kani-vscode-extension/blob/3c805273e201505eb576235505252f5cb02fcb86/src/model/kaniRunner.ts#L20

**Comment by jaisnan** [comment] 2023-05-17 21:41
For this issue, i was thinking of what we could do. One of the solutions is to do this -

`find "$(cd ..; pwd)" -name "cargo-kani"` to get all directories with `cargo-kani `. Then, we link to the installed path by default but if there are multiple options, we can throw a popup asking which of these kani builds to use and then link to that.

As of now, we use 'which cargo-kani' to get the file path to cargo-kani but I think `which` only searches under a specific directory structure, so using find might be a better approach to link the development version of kani.

@feliperodri @celinval , thoughts?

**Comment by feliperodri** [comment] 2023-05-19 19:41
We actually tested the current solution using `which cargo-kani` and it seems to be reliable even when getting Kani from source. We may close this for now.

**Closed by feliperodri** 2023-05-19 19:41 UTC
Labels: bug, must-have
